stages:
  load_data:
    cmd: python src/stage-01-load-save.py --config=config/config.yaml
    deps:
      - src/stage-01-load-save.py
      - src/utils/utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv